### PR TITLE
Landing page

### PR DESCRIPTION
**Pull request by chibuike07**
Done with with landing page UI

### CODE REVIEW

**Review by Dolapo-Mosuro — APPROVED** [review]

**Review by HENRYKC24 — COMMENTED** [review]
This is a great work you have done. Thank you so much and keep up the good work. I only have to point out to you that the page is not responsive. There are some components that really don't align well in mobile viewport. Eg.
Screenshot from 2020-09-20 20-00-28

I think that those components should wrap to be displayed one each in a row on mobile view. Thanks

**Review by Krypton-Creation — APPROVED** [review]

**Comment by Krypton-Creation** [comment]
Aside the responsiveness which I know with all certainty would be fixed, this is just so amazing. Weldone guys.

**Review by emmyclef — APPROVED** [review]

**Comment by chibuike07** [comment]
> This is a great work you have done. Thank you so much and keep up the good work. I only have to point out to you that the page is not responsive. There are some components that really don't align well in mobile viewport. Eg.
> Screenshot from 2020-09-20 20-00-28
> 
> I think that those components should wrap to be displayed one each in a row on mobile view. Thanks
> 

Sure noted. On the view point, that will be finalized once the mobile display screen is ready. Thanks

**Comment by chibuike07** [comment]
The landing page web view has been approved.

**Pull request closed without merging**
